services:
  ewm-db:
    image: postgres:16.1
    container_name: ewm-db

    ports:
      - "5434:5432"

    environment:
      POSTGRES_DB: ewm
      POSTGRES_USER: ewm
      POSTGRES_PASSWORD: ewm

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ewm -d ewm"]
      interval: 5s
      timeout: 5s
      retries: 10

    volumes:
      - ewm-db-data:/var/lib/postgresql/data

  stats-db:
    image: postgres:16.1
    container_name: stats-db

    ports:
      - "5433:5432"

    environment:
      POSTGRES_DB: stats
      POSTGRES_USER: stats
      POSTGRES_PASSWORD: stats

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stats -d stats"]
      interval: 5s
      timeout: 5s
      retries: 10

    volumes:
      - stats-db-data:/var/lib/postgresql/data

volumes:
  ewm-db-data:
  stats-db-data: