services:
  admin-db:
    image: postgres:16.1
    container_name: admin-db

    ports:
      - "5434:5432"

    environment:
      POSTGRES_DB: admin_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d admin_db" ]
      interval: 5s
      timeout: 5s
      retries: 10

    volumes:
      - admin-db-data:/var/lib/postgresql/data

  events-db:
    image: postgres:16.1
    container_name: events-db

    ports:
      - "5435:5432"

    environment:
      POSTGRES_DB: events_db
      POSTGRES_USER: events
      POSTGRES_PASSWORD: events

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U events -d events_db" ]
      interval: 5s
      timeout: 5s
      retries: 10

    volumes:
      - events-db-data:/var/lib/postgresql/data

  request-db:
    image: postgres:16.1
    container_name: request-db

    ports:
      - "5437:5432"

    environment:
      POSTGRES_DB: request_db
      POSTGRES_USER: request
      POSTGRES_PASSWORD: request

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U request -d request_db" ]
      interval: 5s
      timeout: 5s
      retries: 10

    volumes:
      - request-db-data:/var/lib/postgresql/data

  stats-db:
    image: postgres:16.1
    container_name: stats-db

    ports:
      - "5433:5432"

    environment:
      POSTGRES_DB: stats
      POSTGRES_USER: stats
      POSTGRES_PASSWORD: stats

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U stats -d stats" ]
      interval: 5s
      timeout: 5s
      retries: 10

    volumes:
      - stats-db-data:/var/lib/postgresql/data

volumes:
  admin-db-data:
  events-db-data:
  request-db-data:
  stats-db-data: