services:
  discovery-server:
    build: infra/discovery-server
    image: discovery-server
    ports:
      - "8761:8761"

  config-server:
    build: infra/config-server
    image: config-server

    depends_on:
      discovery-server:
        condition: service_started

    ports:
      - "8888:8888"

    environment:
      SERVER_PORT: 8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/

  gateway-server:
    build: infra/gateway-server
    image: gateway-server

    depends_on:
      discovery-server:
        condition: service_started

    ports:
      - "8080:8080"

    environment:
      CONFIG_SERVER_URL: http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/

  stats-db:
    image: postgres:16.1

    ports:
      - "5433:5432"

    environment:
      POSTGRES_DB: stats
      POSTGRES_USER: stats
      POSTGRES_PASSWORD: stats

    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      interval: 5s
      timeout: 5s
      retries: 10

  stats-server:
    build: stats-service/stats-server
    image: stats-server

    depends_on:
      stats-db:
        condition: service_healthy
      config-server:
        condition: service_started

    environment:
      CONFIG_SERVER_URL: http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/

      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/stats
      SPRING_DATASOURCE_USERNAME: stats
      SPRING_DATASOURCE_PASSWORD: stats

  ewm-db:
    image: postgres:16.1

    ports:
      - "5432:5432"

    environment:
      POSTGRES_DB: ewm
      POSTGRES_USER: ewm
      POSTGRES_PASSWORD: ewm

    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      interval: 5s
      timeout: 5s
      retries: 10

  ewm-main-service:
    build: core/main-service
    image: ewm-main-service

    depends_on:
      ewm-db:
        condition: service_healthy
      config-server:
        condition: service_started

    environment:
      CONFIG_SERVER_URL: http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/

      SPRING_DATASOURCE_URL: jdbc:postgresql://ewm-db:5432/ewm
      SPRING_DATASOURCE_USERNAME: ewm
      SPRING_DATASOURCE_PASSWORD: ewm