spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/stats}
    username: ${SPRING_DATASOURCE_USERNAME:stats}
    password: ${SPRING_DATASOURCE_PASSWORD:stats}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        format_sql: true

server:
  port: 9090