spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/request_db}
    username: ${SPRING_DATASOURCE_USERNAME:request}
    password: ${SPRING_DATASOURCE_PASSWORD:request}
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true

server:
  port: 0

management:
  endpoints:
    web:
      exposure:
        include: health,info

resilience4j:
  retry:
    instances:
      default:
        max-attempts: 3
        wait-duration: 500ms
  circuitbreaker:
    instances:
      default:
        sliding-window-size: 10
        failure-rate-threshold: 50
