CREATE TABLE IF NOT EXISTS user_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    event_id BIGINT NOT NULL,
    requester_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    CONSTRAINT uq_user_requests_event_requester UNIQUE (event_id, requester_id),
    CONSTRAINT chk_user_requests_status CHECK (status IN ('PENDING', 'CONFIRMED', 'REJECTED', 'CANCELED'))
);

CREATE INDEX IF NOT EXISTS idx_user_requests_event_id ON user_requests (event_id);
CREATE INDEX IF NOT EXISTS idx_user_requests_requester_id ON user_requests (requester_id);
CREATE INDEX IF NOT EXISTS idx_user_requests_event_status ON user_requests (event_id, status);
