logging:
  level:
    org.springframework.cloud.gateway: TRACE
    reactor.netty.http.client: DEBUG

server:
  port: 8080

spring:
  application:
    name: gateway-server

  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/admin/users/**

        - id: events-service
          uri: lb://events-service
          predicates:
            - Path=/events/**,/users/*/events/**,/admin/events/**

        - id: request-service
          uri: lb://request-service
          predicates:
            - Path=/users/*/requests/**,/users/*/events/*/requests/**

        - id: common-service
          uri: lb://common-service
          predicates:
            - Path=/categories/**,/compilations/**,/comments/**,/users/*/comments/**,/admin/categories/**,/admin/compilations/**,/admin/comments/**

        - id: main-service
          uri: lb://main-service
          predicates:
            - Path=/admin/**,/users/**,/events/**,/categories/**,/compilations/**,/comments/**

        - id: stats-server
          uri: lb://stats-server
          predicates:
            - Path=/hit,/stats


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}