server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: ewm-main-service
          uri: lb://ewm-main-service
          predicates:
            - Path=/admin/**,/users/**,/events/**,/categories/**,/compilations/**,/comments/**