spring:
  application:
    name: event-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  cloud:
    openfeign:
      okhttp:
        enabled: true
    config:
      discovery:
        enabled: true
        service-id: config-server

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

server:
  port: ${SERVER_PORT:0}

grpc:
  client:
    collector:
      address: 'discovery:///collector'
      negotiationType: plaintext
    analyzer:
      address: 'discovery:///analyzer'
      negotiationType: plaintext
