spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ewm}
    username: ${SPRING_DATASOURCE_USERNAME:ewm}
    password: ${SPRING_DATASOURCE_PASSWORD:ewm}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        format_sql: true

server:
  port: 8081