spring:
  application:
    name: ewm-main-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ewm}
    username: ${SPRING_DATASOURCE_USERNAME:ewm}
    password: ${SPRING_DATASOURCE_PASSWORD:ewm}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd HH:mm:ss
    deserialization:
      adjust-dates-to-context-time-zone: false

server:
  port: 0

stats:
  server:
    url: http://stats-server