syntax = "proto3";
package stats.service.analyzer;
option java_multiple_files = true;
option java_package = "ru.practicum.ewm.stats.proto";

import "stats.proto";

service RecommendationsController {
  rpc GetRecommendationsForUser(stats.message.UserPredictionsRequestProto) returns (stream stats.message.RecommendedEventProto);
  rpc GetSimilarEvents(stats.message.SimilarEventsRequestProto) returns (stream stats.message.RecommendedEventProto);
  rpc GetInteractionsCount(stats.message.InteractionsCountRequestProto) returns (stream stats.message.RecommendedEventProto);
}
