spring.application.name=ewm-main-service
server.port=8080

# Database
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ewm}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:ewm}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:ewm}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.deserialization.adjust-dates-to-context-time-zone=false

stats.server.url=${STATS_SERVER_URL:http://localhost:9090}
